// flow-typed signature: 6cddbfbdaa927f75e5b65d8742151c46
// flow-typed version: <<STUB>>/wrtc_v0.0.62/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wrtc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wrtc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wrtc/dist/wrtc' {
  declare module.exports: any;
}

declare module 'wrtc/examples/bridge' {
  declare module.exports: any;
}

declare module 'wrtc/examples/issue142' {
  declare module.exports: any;
}

declare module 'wrtc/examples/minimal-memory' {
  declare module.exports: any;
}

declare module 'wrtc/examples/nop' {
  declare module.exports: any;
}

declare module 'wrtc/examples/peer' {
  declare module.exports: any;
}

declare module 'wrtc/examples/ping-pong-test' {
  declare module.exports: any;
}

declare module 'wrtc/examples/sanity-test' {
  declare module.exports: any;
}

declare module 'wrtc/examples/test' {
  declare module.exports: any;
}

declare module 'wrtc/lib/browser' {
  declare module.exports: any;
}

declare module 'wrtc/lib/datachannel' {
  declare module.exports: any;
}

declare module 'wrtc/lib/datachannelevent' {
  declare module.exports: any;
}

declare module 'wrtc/lib/datachannelmessageevent' {
  declare module.exports: any;
}

declare module 'wrtc/lib/error' {
  declare module.exports: any;
}

declare module 'wrtc/lib/eventtarget' {
  declare module.exports: any;
}

declare module 'wrtc/lib/icecandidate' {
  declare module.exports: any;
}

declare module 'wrtc/lib/index' {
  declare module.exports: any;
}

declare module 'wrtc/lib/peerconnection' {
  declare module.exports: any;
}

declare module 'wrtc/lib/rtcpeerconnectioniceevent' {
  declare module.exports: any;
}

declare module 'wrtc/lib/rtcstatsreport' {
  declare module.exports: any;
}

declare module 'wrtc/lib/rtcstatsresponse' {
  declare module.exports: any;
}

declare module 'wrtc/lib/sessiondescription' {
  declare module.exports: any;
}

declare module 'wrtc/scripts/download-webrtc-libraries-and-headers' {
  declare module.exports: any;
}

declare module 'wrtc/test/all' {
  declare module.exports: any;
}

declare module 'wrtc/test/bwtest' {
  declare module.exports: any;
}

declare module 'wrtc/test/connect' {
  declare module.exports: any;
}

declare module 'wrtc/test/create-offer' {
  declare module.exports: any;
}

declare module 'wrtc/test/helpers/capture-candidates' {
  declare module.exports: any;
}

declare module 'wrtc/test/iceservers' {
  declare module.exports: any;
}

declare module 'wrtc/test/multiconnect' {
  declare module.exports: any;
}

declare module 'wrtc/test/sessiondesc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wrtc/dist/wrtc.js' {
  declare module.exports: $Exports<'wrtc/dist/wrtc'>;
}
declare module 'wrtc/examples/bridge.js' {
  declare module.exports: $Exports<'wrtc/examples/bridge'>;
}
declare module 'wrtc/examples/issue142.js' {
  declare module.exports: $Exports<'wrtc/examples/issue142'>;
}
declare module 'wrtc/examples/minimal-memory.js' {
  declare module.exports: $Exports<'wrtc/examples/minimal-memory'>;
}
declare module 'wrtc/examples/nop.js' {
  declare module.exports: $Exports<'wrtc/examples/nop'>;
}
declare module 'wrtc/examples/peer.js' {
  declare module.exports: $Exports<'wrtc/examples/peer'>;
}
declare module 'wrtc/examples/ping-pong-test.js' {
  declare module.exports: $Exports<'wrtc/examples/ping-pong-test'>;
}
declare module 'wrtc/examples/sanity-test.js' {
  declare module.exports: $Exports<'wrtc/examples/sanity-test'>;
}
declare module 'wrtc/examples/test.js' {
  declare module.exports: $Exports<'wrtc/examples/test'>;
}
declare module 'wrtc/lib/browser.js' {
  declare module.exports: $Exports<'wrtc/lib/browser'>;
}
declare module 'wrtc/lib/datachannel.js' {
  declare module.exports: $Exports<'wrtc/lib/datachannel'>;
}
declare module 'wrtc/lib/datachannelevent.js' {
  declare module.exports: $Exports<'wrtc/lib/datachannelevent'>;
}
declare module 'wrtc/lib/datachannelmessageevent.js' {
  declare module.exports: $Exports<'wrtc/lib/datachannelmessageevent'>;
}
declare module 'wrtc/lib/error.js' {
  declare module.exports: $Exports<'wrtc/lib/error'>;
}
declare module 'wrtc/lib/eventtarget.js' {
  declare module.exports: $Exports<'wrtc/lib/eventtarget'>;
}
declare module 'wrtc/lib/icecandidate.js' {
  declare module.exports: $Exports<'wrtc/lib/icecandidate'>;
}
declare module 'wrtc/lib/index.js' {
  declare module.exports: $Exports<'wrtc/lib/index'>;
}
declare module 'wrtc/lib/peerconnection.js' {
  declare module.exports: $Exports<'wrtc/lib/peerconnection'>;
}
declare module 'wrtc/lib/rtcpeerconnectioniceevent.js' {
  declare module.exports: $Exports<'wrtc/lib/rtcpeerconnectioniceevent'>;
}
declare module 'wrtc/lib/rtcstatsreport.js' {
  declare module.exports: $Exports<'wrtc/lib/rtcstatsreport'>;
}
declare module 'wrtc/lib/rtcstatsresponse.js' {
  declare module.exports: $Exports<'wrtc/lib/rtcstatsresponse'>;
}
declare module 'wrtc/lib/sessiondescription.js' {
  declare module.exports: $Exports<'wrtc/lib/sessiondescription'>;
}
declare module 'wrtc/scripts/download-webrtc-libraries-and-headers.js' {
  declare module.exports: $Exports<'wrtc/scripts/download-webrtc-libraries-and-headers'>;
}
declare module 'wrtc/test/all.js' {
  declare module.exports: $Exports<'wrtc/test/all'>;
}
declare module 'wrtc/test/bwtest.js' {
  declare module.exports: $Exports<'wrtc/test/bwtest'>;
}
declare module 'wrtc/test/connect.js' {
  declare module.exports: $Exports<'wrtc/test/connect'>;
}
declare module 'wrtc/test/create-offer.js' {
  declare module.exports: $Exports<'wrtc/test/create-offer'>;
}
declare module 'wrtc/test/helpers/capture-candidates.js' {
  declare module.exports: $Exports<'wrtc/test/helpers/capture-candidates'>;
}
declare module 'wrtc/test/iceservers.js' {
  declare module.exports: $Exports<'wrtc/test/iceservers'>;
}
declare module 'wrtc/test/multiconnect.js' {
  declare module.exports: $Exports<'wrtc/test/multiconnect'>;
}
declare module 'wrtc/test/sessiondesc.js' {
  declare module.exports: $Exports<'wrtc/test/sessiondesc'>;
}
